In [1]:
import numpy as np 
import pandas as pd
data = pd.Series([0.25, 0.5, 0.75, 1.0]) 
data


0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [2]:
print(data.values)
print(data.index)

[0.25 0.5  0.75 1.  ]
RangeIndex(start=0, stop=4, step=1)


In [3]:
print(data[1])
print(data[1:3])

0.5
1    0.50
2    0.75
dtype: float64


In [4]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [5]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [6]:
population_dict = {'California': 38332521, 'Texas': 26448193,
                               'New York': 19651127,
                               'Florida': 19552860,
                               'Illinois': 12882135}
population = pd.Series(population_dict) 
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [7]:
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [8]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
                 'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict) 
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [9]:
states = pd.DataFrame({'population': population, 'area': area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [10]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [11]:
states.columns

Index(['population', 'area'], dtype='object')

In [12]:
data = [{'a': i, 'b': 2 * i} for i in range(3)]
data

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]

In [13]:
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [14]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [16]:
type(population)

pandas.core.series.Series

In [17]:
pd.DataFrame({'population': population, 'area': area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [20]:
population_dict2 = {'California': 38332521, 'Texas': 26448193,
                               'New York': 19651127,
                               'Florida': 19552860,
                               'Illinois': 12882135,
                   'DC':10000}
population2 = pd.Series(population_dict2)
pd.DataFrame({'population2': population2, 'area': area})

population2      area
California     38332521  423967.0
DC                10000       NaN
Florida        19552860  170312.0
Illinois       12882135  149995.0
New York       19651127  141297.0
Texas          26448193  695662.0

In [21]:
pd.DataFrame(np.random.rand(3, 2), 
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

foo       bar
a  0.630440  0.602671
b  0.478404  0.860628
c  0.674212  0.296149

In [23]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [24]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [25]:
indA = pd.Index([1, 3, 5, 7, 9]) 
indB = pd.Index([2, 3, 5, 7, 11])

In [26]:
indA & indB

Int64Index([3, 5, 7], dtype='int64')

In [27]:
indA ^ indB

Int64Index([1, 2, 9, 11], dtype='int64')

In [28]:
import pandas as pd
data = pd.Series([0.25, 0.5, 0.75, 1.0],index=['a', 'b', 'c', 'd'])               
    
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [29]:
'a' in data

True

In [30]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [31]:
data['e'] = 1.25
data
data['e'] = 1.2
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.20
dtype: float64

In [32]:
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [33]:
data[0:2]

a    0.25
b    0.50
dtype: float64

In [34]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [35]:
# fancy indexing 
data[['a', 'e']]

a    0.25
e    1.20
dtype: float64

In [37]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5]) 
data

1    a
3    b
5    c
dtype: object

In [38]:
data[1]

'a'

In [39]:
data[1:3]

3    b
5    c
dtype: object

In [40]:
data.loc[1:3]

1    a
3    b
dtype: object

In [41]:
data.iloc[1:3] #iloc is the same as data[1:3]

3    b
5    c
dtype: object

In [42]:
area = pd.Series({'California': 423967, 'Texas': 695662, 'New York': 141297, 'Florida': 170312,
'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [43]:
data.area is data['area']

True

In [44]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [47]:
type(data.values)

numpy.ndarray

In [48]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [49]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [50]:
type(data.values[0])

numpy.ndarray

In [51]:
data.values[0].shape

(3,)

In [52]:
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [54]:
data.iloc[:2, :2]

area       pop
California  423967  38332521
Texas       695662  26448193

In [56]:
data.loc[:'Illinois', :'area']

area
California  423967
Texas       695662
New York    141297
Florida     170312
Illinois    149995

In [58]:
data.loc[data.density > 100, ['pop', 'area','density']]

pop    area     density
New York  19651127  141297  139.076746
Florida   19552860  170312  114.806121

In [60]:
data.iloc[0, 2] = 90 
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [61]:
data['Florida':'Illinois']

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [63]:
data.loc['Florida':'Illinois','area':'density']

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [64]:
data[1:3] 

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [65]:
area = pd.Series({1: 423967, 2: 695662, 3: 141297, 4: 170312,
5: 149995})
pop = pd.Series({1: 10, 2: 20, 3: 30, 4: 40,
5: 50})
data2 = pd.DataFrame({'a':area, 'b':pop})
data2

a   b
1  423967  10
2  695662  20
3  141297  30
4  170312  40
5  149995  50

In [68]:
data2.loc[1:3]

a   b
1  423967  10
2  695662  20
3  141297  30

In [69]:
data2[1:3]   

a   b
2  695662  20
3  141297  30

In [70]:
data2.iloc[1:3]

a   b
2  695662  20
3  141297  30

In [71]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4)) # this series has no explicit index
ser

0    6
1    3
2    7
3    4
dtype: int64

In [88]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)), columns=['A', 'B', 'C', 'D'])
df


A  B  C  D
0  1  7  5  1
1  4  0  9  5
2  8  0  9  2

In [74]:
type(np.exp(ser))

pandas.core.series.Series

In [76]:
np.sin(df * np.pi )

A             B             C             D
0 -7.347881e-16  1.102182e-15 -2.449294e-16 -7.347881e-16
1  8.572528e-16 -4.898587e-16  3.673940e-16  8.572528e-16
2  8.572528e-16 -2.449294e-16  6.123234e-16 -4.898587e-16

In [77]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662, 'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193, 'New York': 19651127}, name='population')

In [79]:
type(population / area)

pandas.core.series.Series

In [80]:
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [81]:
type(area.index)

pandas.core.indexes.base.Index

In [82]:
A = pd.Series([2, 4, 6], index=[0, 1, 2]) 
B = pd.Series([1, 3, 5], index=[1, 2, 3]) 
A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [83]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [93]:
df['A']=df['A'].add(df['B'])
df

A  B  C  D
0  8  7  5  1
1  4  0  9  5
2  8  0  9  2

In [90]:
df

A  B  C  D
0  1  7  5  1
1  4  0  9  5
2  8  0  9  2

In [94]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                 columns=list('AB'))
A

A   B
0  11  19
1   2   4

In [96]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)), columns=list('BAC'))
B

B  A  C
0  2  6  4
1  8  6  1
2  3  8  1

In [97]:
 A + B

A     B   C
0  17.0  21.0 NaN
1   8.0  12.0 NaN
2   NaN   NaN NaN

In [102]:
fill = A.stack()
print(fill)
type(fill) #pandas.core.series.Series

0  A    11
   B    19
1  A     2
   B     4
dtype: int64


pandas.core.series.Series

In [103]:
fill=fill.mean()
print(fill)


9.0
<class 'numpy.float64'>


In [105]:
A.add(B, fill_value=fill)   #should be a float value 

A     B     C
0  17.0  21.0  13.0
1   8.0  12.0  10.0
2  17.0  12.0  10.0

In [109]:
A = rng.randint(10, size=(3, 4))
print(type(A))
A

<class 'numpy.ndarray'>


array([[7, 3, 1, 5],
       [5, 9, 3, 5],
       [1, 9, 1, 9]])

In [110]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-2,  6,  2,  0],
       [-6,  6,  0,  4]])

In [111]:
df = pd.DataFrame(A, columns=list('QRST'))
df

Q  R  S  T
0  7  3  1  5
1  5  9  3  5
2  1  9  1  9

In [113]:
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -2  6  2  0
2 -6  6  0  4

In [114]:
# df.subtract(df['R'], axis=0)
df

Q  R  S  T
0  7  3  1  5
1  5  9  3  5
2  1  9  1  9

In [115]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0  4  0 -2  2
1 -4  0 -6 -4
2 -8  0 -8  0

In [116]:
df

Q  R  S  T
0  7  3  1  5
1  5  9  3  5
2  1  9  1  9

In [118]:
halfrow = df.iloc[0, ::2] 
print(type(halfrow))
halfrow

<class 'pandas.core.series.Series'>


Q    7
S    1
Name: 0, dtype: int64

In [125]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -2.0 NaN  2.0 NaN
2 -6.0 NaN  0.0 NaN

In [126]:
vals1 = np.array([1, None, 3, 4]) 
vals1


array([1, None, 3, 4], dtype=object)

In [127]:
vals2 = np.array([1, np.nan, 3, 4]) 
vals2.dtype

dtype('float64')

In [128]:
np.nansum(vals2)

8.0

In [131]:
x = pd.Series(range(1,10,2), dtype=int)
x

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [137]:
x[0]=None
x

0    NaN
1    3.0
2    5.0
3    7.0
4    9.0
dtype: float64

In [138]:
data = pd.Series([1, np.nan, 'hello', None])

In [141]:
print(data.isnull())
type(data.isnull())

0    False
1     True
2    False
3     True
dtype: bool


pandas.core.series.Series

In [142]:
data.notnull()

0     True
1    False
2     True
3    False
dtype: bool

In [143]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [144]:
data.dropna()

0        1
2    hello
dtype: object

In [145]:
df = pd.DataFrame([[1, np.nan, 2], [2, 3, 5],[np.nan, 4, 6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [146]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [148]:
df[3] = np.nan 
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [149]:
df.dropna(axis='columns', how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [150]:
df.dropna(axis='columns', how='any')

2
0  2
1  5
2  6

In [154]:
df.dropna(axis='columns', thresh=2)

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [160]:
data = pd.DataFrame(([1, np.nan, 2, None, 3] for i in range(3)), columns=list('abcde'))
data

a   b  c     d  e
0  1 NaN  2  None  3
1  1 NaN  2  None  3
2  1 NaN  2  None  3

In [161]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [162]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [164]:
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,18976457, 19378102,20851820, 25145561]
pop = pd.Series(populations, index=index) 
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [165]:
pop[('California', 2010):('Texas', 2000)]


(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
dtype: int64

In [225]:
#pop.loc[[i for i in pop.index if i[1] == 2010]]
pop[[i for i in pop.index if i[1] == 2010]]

California  2010    37253956
New York    2010    19378102
Texas       2010    25145561
dtype: int64

In [167]:
index = pd.MultiIndex.from_tuples(index) 
index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [170]:
pop = pd.Series(populations, index=index) 
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [209]:
pop['Texas',]

2000    20851820
2010    25145561
dtype: int64

In [211]:
pop[:,2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [213]:
pop['Texas',2000]

20851820

In [221]:
pop.loc['New York':'Texas',2000:2010]

New York  2000    18976457
          2010    19378102
Texas     2000    20851820
          2010    25145561
dtype: int64

In [228]:
print(type(pop))
pop

<class 'pandas.core.series.Series'>


California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [229]:
pop_df = pop.unstack()
print(type(pop_df))
pop_df

<class 'pandas.core.frame.DataFrame'>


2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [232]:
#stack and unstack changes between series and datafream in this occasion
print(pop_df.stack())
print(type(pop_df.stack()))


California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64
<class 'pandas.core.series.Series'>


In [233]:
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [234]:
pop_df = pd.DataFrame({'total': pop,
'under18': [9267089, 9284094,4687374, 4318033,5906301, 6879014]})
pop_df

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [235]:
pop_df.index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [236]:
pop_df.columns

Index(['total', 'under18'], dtype='object')

In [238]:
f_u18 = pop_df['under18'] / pop_df['total'] 
# f_u18.unstack()
print(f_u18)
print(type(f_u18))
f_u18.unstack()


California  2000    0.273594
            2010    0.249211
New York    2000    0.247010
            2010    0.222831
Texas       2000    0.283251
            2010    0.273568
dtype: float64
<class 'pandas.core.series.Series'>


2000      2010
California  0.273594  0.249211
New York    0.247010  0.222831
Texas       0.283251  0.273568

In [239]:
df = pd.DataFrame(np.random.rand(4, 2),
index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],columns=['data1', 'data2'])
df


data1     data2
a 1  0.517566  0.142625
  2  0.452191  0.452892
b 1  0.928379  0.659457
  2  0.005669  0.198990

In [243]:
data = {            ('California', 2000): 33871648,
                    ('California', 2010): 37253956,
                    ('Texas', 2000): 20851820,
                    ('Texas', 2010): 25145561,
                    ('New York', 2000): 18976457,
                    ('New York', 2010): 19378102
       }
# pd.Series(data)
pd.DataFrame(pd.Series(data),columns=['pop'])
# pd.DataFrame

pop
California 2000  33871648
           2010  37253956
Texas      2000  20851820
           2010  25145561
New York   2000  18976457
           2010  19378102

In [244]:
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b'], [1, 2, 1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [245]:
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [246]:
pd.MultiIndex.from_product([['a', 'b'], [1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [250]:
# pd.MultiIndex(levels=[['a', 'b'], [1, 2]])
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [252]:
pop.index.names = ['state', 'year']
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [253]:
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],names=['year', 'visit'])
print(index)
print(type(index))

MultiIndex([(2013, 1),
            (2013, 2),
            (2014, 1),
            (2014, 2)],
           names=['year', 'visit'])
<class 'pandas.core.indexes.multi.MultiIndex'>


In [254]:
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
                                     names=['subject', 'type'])
columns

MultiIndex([(  'Bob',   'HR'),
            (  'Bob', 'Temp'),
            ('Guido',   'HR'),
            ('Guido', 'Temp'),
            (  'Sue',   'HR'),
            (  'Sue', 'Temp')],
           names=['subject', 'type'])

In [255]:
data = np.round(np.random.randn(4, 6), 1)
print(data)
data[:, ::2] *= 10
print(data)
data += 37
print(data)

[[-0.1  0.6 -0.1 -0.2  1.4  0.9]
 [ 1.6  0.3 -2.8 -0.2 -0.6 -0.5]
 [ 1.1  0.7 -0.1 -0.4 -1.1 -1.2]
 [-0.6 -0.8  1.6  0.1 -0.3  0.2]]
[[ -1.    0.6  -1.   -0.2  14.    0.9]
 [ 16.    0.3 -28.   -0.2  -6.   -0.5]
 [ 11.    0.7  -1.   -0.4 -11.   -1.2]
 [ -6.   -0.8  16.    0.1  -3.    0.2]]
[[36.  37.6 36.  36.8 51.  37.9]
 [53.  37.3  9.  36.8 31.  36.5]
 [48.  37.7 36.  36.6 26.  35.8]
 [31.  36.2 53.  37.1 34.  37.2]]


In [256]:
health_data = pd.DataFrame(data, index=index, columns=columns)
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      36.0  37.6  36.0  36.8  51.0  37.9
     2      53.0  37.3   9.0  36.8  31.0  36.5
2014 1      48.0  37.7  36.0  36.6  26.0  35.8
     2      31.0  36.2  53.0  37.1  34.0  37.2

In [267]:
health_data.loc[2013]

subject   Bob       Guido         Sue      
type       HR  Temp    HR  Temp    HR  Temp
visit                                      
1        36.0  37.6  36.0  36.8  51.0  37.9
2        53.0  37.3   9.0  36.8  31.0  36.5

In [268]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [269]:
pop['California', 2000]

33871648

In [270]:
print(type(pop['California']))
pop['California']

<class 'pandas.core.series.Series'>


year
2000    33871648
2010    37253956
dtype: int64

In [272]:
type(pop.loc['California':'New York'])

pandas.core.series.Series

In [273]:
pop[:, 2000]

state
California    33871648
New York      18976457
Texas         20851820
dtype: int64

In [276]:
type(pop[pop > 22000000])
pop[pop > 22000000]

state       year
California  2000    33871648
            2010    37253956
Texas       2010    25145561
dtype: int64

In [281]:
type(pop_df[pop_df['total']>100])

pandas.core.frame.DataFrame

In [282]:
pop[['California', 'Texas']]

state       year
California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
dtype: int64

In [283]:
pop.loc['California', 2000:2010]

state       year
California  2000    33871648
            2010    37253956
dtype: int64

In [284]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      36.0  37.6  36.0  36.8  51.0  37.9
     2      53.0  37.3   9.0  36.8  31.0  36.5
2014 1      48.0  37.7  36.0  36.6  26.0  35.8
     2      31.0  36.2  53.0  37.1  34.0  37.2

In [285]:
health_data['Guido', 'HR']

year  visit
2013  1        36.0
      2         9.0
2014  1        36.0
      2        53.0
Name: (Guido, HR), dtype: float64

In [294]:
print(health_data.loc[2013,1]['Bob']['HR'])
print(health_data.loc[2013,1]['Bob','HR'])


36.0
36.0


In [297]:
health_data.iloc[:2, :2]#when you use iloc ,you kinda bypass all indexes

subject      Bob      
type          HR  Temp
year visit            
2013 1      36.0  37.6
     2      53.0  37.3

In [298]:
health_data.loc[:, ('Bob', 'HR')]

year  visit
2013  1        36.0
      2        53.0
2014  1        48.0
      2        31.0
Name: (Bob, HR), dtype: float64

In [305]:
health_data.loc[:, 'Bob':('Guido','HR')]

subject      Bob       Guido
type          HR  Temp    HR
year visit                  
2013 1      36.0  37.6  36.0
     2      53.0  37.3   9.0
2014 1      48.0  37.7  36.0
     2      31.0  36.2  53.0

In [306]:
health_data.loc[:, ('Bob','Temp'):('Guido','HR')]

subject      Bob Guido
type        Temp    HR
year visit            
2013 1      37.6  36.0
     2      37.3   9.0
2014 1      37.7  36.0
     2      36.2  53.0

In [310]:
health_data.loc[(2013,2):(2014,1), ('Bob'):('Guido')]

subject      Bob       Guido      
type          HR  Temp    HR  Temp
year visit                        
2013 2      53.0  37.3   9.0  36.8
2014 1      48.0  37.7  36.0  36.6

In [315]:
health_data.loc[(2013,2):(2014,1), (('Bob','HR'),('Guido','HR'))]

subject      Bob
type          HR
year visit      
2013 2      53.0
2014 1      48.0

In [323]:
health_data.loc[(2013,2), ('Guido','HR')]

9.0

In [328]:
health_data.loc[(2013,1), ('Bob')]

type
HR      36.0
Temp    37.6
Name: (2013, 1), dtype: float64

In [329]:
health_data.loc[2013, ('Bob')]

type     HR  Temp
visit            
1      36.0  37.6
2      53.0  37.3

In [332]:
health_data.loc[:, [('Bob','HR'),('Guido','HR')]]


subject      Bob Guido
type          HR    HR
year visit            
2013 1      36.0  36.0
     2      53.0   9.0
2014 1      48.0  36.0
     2      31.0  53.0

In [333]:
health_data.loc[(2013,2):(2014,1), [('Bob','HR'),('Guido','HR')]]

subject      Bob Guido
type          HR    HR
year visit            
2013 2      53.0   9.0
2014 1      48.0  36.0

In [335]:
health_data.loc[[(2013,1),(2014,1)], [('Bob','HR'),('Guido','HR')]]

subject      Bob Guido
type          HR    HR
year visit            
2013 1      36.0  36.0
2014 1      48.0  36.0

In [338]:
#accessing directly
health_data.loc[2013][[('Bob','HR'),('Guido','HR')]]

subject   Bob Guido
type       HR    HR
visit              
1        36.0  36.0
2        53.0   9.0

In [349]:
#slicing
idx = pd.IndexSlice 
health_data.loc[idx[:2013, 1], idx['Guido':'Sue', 'HR':'Temp']]

subject    Guido         Sue      
type          HR  Temp    HR  Temp
year visit                        
2013 1      36.0  36.8  51.0  37.9

In [356]:
# health_data.loc[2013]['Bob']['HR']
health_data.loc[2013]['Bob','HR']

visit
1    36.0
2    53.0
Name: (Bob, HR), dtype: float64

In [359]:
print(type(idx[:2013, 1]))
idx[:2013, 1]

<class 'tuple'>


(slice(None, 2013, None), 1)

In [365]:
health_data.loc[(2013,1):(2014,1)]

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      36.0  37.6  36.0  36.8  51.0  37.9
     2      53.0  37.3   9.0  36.8  31.0  36.5
2014 1      48.0  37.7  36.0  36.6  26.0  35.8

In [360]:
index = pd.MultiIndex.from_product([['a', 'c', 'b'], [1, 2]])
data = pd.Series(np.random.rand(6), index=index)
data.index.names = ['char', 'int']
data

char  int
a     1      0.304914
      2      0.000655
c     1      0.119872
      2      0.814928
b     1      0.009713
      2      0.184727
dtype: float64

In [366]:
data = data.sort_index() 
data

char  int
a     1      0.304914
      2      0.000655
b     1      0.009713
      2      0.184727
c     1      0.119872
      2      0.814928
dtype: float64

In [369]:
data[('a',1):('b',1)]

char  int
a     1      0.304914
      2      0.000655
b     1      0.009713
dtype: float64

In [375]:
data[('a',):('b',1)]

char  int
a     1      0.304914
      2      0.000655
b     1      0.009713
dtype: float64

In [376]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [377]:
pop.unstack(level=0)

state  California  New York     Texas
year                                 
2000     33871648  18976457  20851820
2010     37253956  19378102  25145561

In [378]:
pop.unstack(level=1)

year            2000      2010
state                         
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [382]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [391]:
pop_flat = pop.reset_index(name='popuation') 
pop_flat

state  year  popuation
0  California  2000   33871648
1  California  2010   37253956
2    New York  2000   18976457
3    New York  2010   19378102
4       Texas  2000   20851820
5       Texas  2010   25145561

In [392]:
pop_flat.set_index(['state', 'year'])

popuation
state      year           
California 2000   33871648
           2010   37253956
New York   2000   18976457
           2010   19378102
Texas      2000   20851820
           2010   25145561

In [393]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      36.0  37.6  36.0  36.8  51.0  37.9
     2      53.0  37.3   9.0  36.8  31.0  36.5
2014 1      48.0  37.7  36.0  36.6  26.0  35.8
     2      31.0  36.2  53.0  37.1  34.0  37.2

In [394]:
data_mean = health_data.mean(level='year') 
data_mean

subject   Bob        Guido          Sue      
type       HR   Temp    HR   Temp    HR  Temp
year                                         
2013     44.5  37.45  22.5  36.80  41.0  37.2
2014     39.5  36.95  44.5  36.85  30.0  36.5

In [413]:
data_mean.mean(axis=1, level='type')

type    HR       Temp
year                 
2013  36.0  37.150000
2014  38.0  36.766667

In [414]:
health_data.loc[2013:2014, ('Bob')].mean(level='year')

type    HR   Temp
year             
2013  44.5  37.45
2014  39.5  36.95

In [416]:
health_data.loc[2013:2014, ('Bob')].mean()

type
HR      42.0
Temp    37.2
dtype: float64

In [417]:
health_data.loc[2013:2014, ('Bob')]

type          HR  Temp
year visit            
2013 1      36.0  37.6
     2      53.0  37.3
2014 1      48.0  37.7
     2      31.0  36.2

In [421]:
def make_df(cols, ind):
    data = {c: [str(c) + str(i) for i in ind] for c in cols}
    print(data)
    return pd.DataFrame(data, ind) # example DataFrame

make_df('ABC', range(3))


{'A': ['A0', 'A1', 'A2'], 'B': ['B0', 'B1', 'B2'], 'C': ['C0', 'C1', 'C2']}


A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [427]:
x=[1,2,3] 
y=[4,5,6] 
z=[7,8,9]
np.concatenate([x, y, z])

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [424]:
x = [[1, 2],[3, 4]]
np.concatenate([x, x], axis=0)

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [428]:
x = [[1, 2],[3, 4]]
np.concatenate([x, x], axis=0)


array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [432]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3]) 
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6]) 

print(type(pd.concat([ser1, ser2])))
pd.concat([ser1, ser2])

<class 'pandas.core.series.Series'>


1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [435]:
df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3, 4])
print(df1)
print(df2)
print(pd.concat([df1, df2]))

{'A': ['A1', 'A2'], 'B': ['B1', 'B2']}
{'A': ['A3', 'A4'], 'B': ['B3', 'B4']}
    A   B
1  A1  B1
2  A2  B2
    A   B
3  A3  B3
4  A4  B4
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4


In [438]:
df3 = make_df('AB', [0, 1]) 
df4 = make_df('CD', [0, 1])
print(df3); 
print(df4); 
print(pd.concat([df3, df4], axis=1))

{'A': ['A0', 'A1'], 'B': ['B0', 'B1']}
{'C': ['C0', 'C1'], 'D': ['D0', 'D1']}
    A   B
0  A0  B0
1  A1  B1
    C   D
0  C0  D0
1  C1  D1
    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1


In [445]:
x = make_df('AB', [0, 1]) 
y = make_df('AB', [2, 3])
print(type(x))
print(y)
y.index = x.index
try:
    pd.concat([x, y], verify_integrity=True)
except ValueError as e: 
    print("ValueError:", e)


{'A': ['A0', 'A1'], 'B': ['B0', 'B1']}
{'A': ['A2', 'A3'], 'B': ['B2', 'B3']}
<class 'pandas.core.frame.DataFrame'>
    A   B
2  A2  B2
3  A3  B3
ValueError: Indexes have overlapping values: Int64Index([0, 1], dtype='int64')


In [446]:
# x y has the same index
print(pd.concat([x, y], ignore_index=True))

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3


In [456]:
pd.concat([x, y,x],keys=['x', 'y','z'] )

A   B
x 0  A0  B0
  1  A1  B1
y 0  A2  B2
  1  A3  B3
z 0  A0  B0
  1  A1  B1

In [472]:
pd.concat([x, y,x],keys=['x', 'y','z'] ).unstack(level=1)

A       B    
    0   1   0   1
x  A0  A1  B0  B1
y  A2  A3  B2  B3
z  A0  A1  B0  B1

In [468]:
pd.concat([x, y,x],keys=['x', 'y','z'] ).reset_index().rename(columns={'level_0': 'a','level_1': 'b'})


a  b   A   B
0  x  0  A0  B0
1  x  1  A1  B1
2  y  0  A2  B2
3  y  1  A3  B3
4  z  0  A0  B0
5  z  1  A1  B1

In [463]:
pd.concat([x,y,x],keys=['x', 'y','z'])

A   B
x 0  A0  B0
  1  A1  B1
y 0  A2  B2
  1  A3  B3
z 0  A0  B0
  1  A1  B1

In [473]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      36.0  37.6  36.0  36.8  51.0  37.9
     2      53.0  37.3   9.0  36.8  31.0  36.5
2014 1      48.0  37.7  36.0  36.6  26.0  35.8
     2      31.0  36.2  53.0  37.1  34.0  37.2

In [480]:
health_data.reset_index(level=1)

subject visit   Bob       Guido         Sue      
type             HR  Temp    HR  Temp    HR  Temp
year                                             
2013        1  36.0  37.6  36.0  36.8  51.0  37.9
2013        2  53.0  37.3   9.0  36.8  31.0  36.5
2014        1  48.0  37.7  36.0  36.6  26.0  35.8
2014        2  31.0  36.2  53.0  37.1  34.0  37.2

In [484]:
pd.concat([x, y,x],keys=['x', 'y','z'] ).reset_index(level=1)

level_1   A   B
x        0  A0  B0
x        1  A1  B1
y        0  A2  B2
y        1  A3  B3
z        0  A0  B0
z        1  A1  B1

In [491]:
def make_df(cols, ind):
    data = {c: [str(c) + str(i) for i in ind] for c in cols}
    print(data)
    return pd.DataFrame(data, ind) # example DataFrame
df5 = make_df('ABC', [1, 2]) 
df6 = make_df('BCD', [3, 4])
print(df5); 
print(df6); 
pd.concat([df5, df6])

{'A': ['A1', 'A2'], 'B': ['B1', 'B2'], 'C': ['C1', 'C2']}
{'B': ['B3', 'B4'], 'C': ['C3', 'C4'], 'D': ['D3', 'D4']}
    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4


A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4

In [494]:
 
df5.index=[1,2]
print(df5);
print(df6); 
print(pd.concat([df5, df6], join='inner'))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4
    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4


In [499]:
print(df5);
print("")
print(df6); 
print("")
print(pd.concat([df5, df6]).reindex([df5.columns]))
      

    A   B   C
1  A1  B1  C1
2  A2  B2  C2

    B   C   D
3  B3  C3  D3
4  B4  C4  D4

     A    B    C    D
A  NaN  NaN  NaN  NaN
B  NaN  NaN  NaN  NaN
C  NaN  NaN  NaN  NaN


In [500]:
print(df1); 
print("")
print(df2);
print("")
df1.append(df2)

    A   B
1  A1  B1
2  A2  B2

    A   B
3  A3  B3
4  A4  B4



A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [507]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue','Me'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR','cs']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]}) 
print(df1)
print()
print(df2)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
4       Me           cs

  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014


In [508]:
df3 = pd.merge(df1, df2)  #discared "me", not found in df2
df3

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [509]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'], 'supervisor': ['Carly', 'Guido', 'Steve']})

In [510]:
print(df3)
print()
print(df4)
pd.merge(df3, df4)

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve


employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

In [511]:
df5 = pd.DataFrame({'group': ['Accounting', 'Accounting', 'Engineering', 'Engineering', 'HR', 'HR'],
                    'skills': ['math', 'spreadsheets', 'coding', 'linux','spreadsheets', 'organization']})

In [513]:
print(df1)
print()
print(df5)
pd.merge(df1, df5)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
4       Me           cs

         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization


employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization

In [515]:
print(df1); 
print();
print(df2); 
pd.merge(df1, df2, on='employee')

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
4       Me           cs

  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014


employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [516]:
df3 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
'salary': [70000, 80000, 120000, 90000]}) 


In [521]:
print(df1); 
print()
print(df3);
pd.merge(df1, df3, left_on="employee", right_on="name")

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
4       Me           cs

   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000


employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000

In [522]:
pd.merge(df1, df3, left_on="employee", right_on="name").drop('name', axis=1)

employee        group  salary
0      Bob   Accounting   70000
1     Jake  Engineering   80000
2     Lisa  Engineering  120000
3      Sue           HR   90000

In [523]:
df1

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
4       Me           cs

In [527]:
df1a = df1.set_index('employee')
df1a

group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR
Me                 cs

In [528]:
df2a = df2.set_index('employee')
df2a

hire_date
employee           
Lisa           2004
Bob            2008
Jake           2012
Sue            2014

In [529]:
print(df1a); 
print()
print(df2a);
pd.merge(df1a, df2a, left_index=True, right_index=True)

                group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR
Me                 cs

          hire_date
employee           
Lisa           2004
Bob            2008
Jake           2012
Sue            2014


group  hire_date
employee                        
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014

In [530]:
print(df1a); 
print()
print(df2a);
df1a.join(df2a)

                group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR
Me                 cs

          hire_date
employee           
Lisa           2004
Bob            2008
Jake           2012
Sue            2014


group  hire_date
employee                        
Bob        Accounting     2008.0
Jake      Engineering     2012.0
Lisa      Engineering     2004.0
Sue                HR     2014.0
Me                 cs        NaN

In [531]:
print(df1a);
print()
print(df3);
pd.merge(df1a, df3, left_index=True, right_on='name')

                group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR
Me                 cs

   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000


group  name  salary
0   Accounting   Bob   70000
1  Engineering  Jake   80000
2  Engineering  Lisa  120000
3           HR   Sue   90000

In [532]:
df1a.rename(index={'Me':'Sue'},inplace=True)
# print()
# print(df2a);
# df1a.join(df2a)

                group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR
Me                 cs


group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR
Sue                cs

In [545]:
print(df1a);
# df3my=df1a.set_index('ID')
print()
print(df3);
pd.merge(df1a, df3, left_index=True, right_index=True)

                group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR
Sue                cs

      salary
name        
Bob    70000
Jake   80000
Lisa  120000
Sue    90000


group  salary
Bob    Accounting   70000
Jake  Engineering   80000
Lisa  Engineering  120000
Sue            HR   90000
Sue            cs   90000

In [546]:
df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'], 'food': ['fish', 'beans', 'bread']},
                    columns=['name', 'food']) 
df7 = pd.DataFrame({'name': ['Mary', 'Joseph'], 'drink': ['wine', 'beer']},
                    columns=['name', 'drink'])


In [549]:
print(df6); 
print()
print(df7); 
pd.merge(df6, df7)


    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread

     name drink
0    Mary  wine
1  Joseph  beer


name   food drink
0  Mary  bread  wine

In [559]:
print(df6); 
print()
print(df7); 
pd.merge(df6, df7, how='right')#you got left right inner outer

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread

     name drink
0    Mary  wine
1  Joseph  beer


name   food drink
0    Mary  bread  wine
1  Joseph    NaN  beer

In [560]:
df8 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'], 'rank': [1, 2, 3, 4]})
df9 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'], 'rank': [3, 1, 4, 2]})

In [562]:
print(df8);
print()
print(df9); 
# pd.merge(df8, df9, on="name")
pd.merge(df8, df9, on="name", suffixes=["_L", "_R"])

   name  rank
0   Bob     1
1  Jake     2
2  Lisa     3
3   Sue     4

   name  rank
0   Bob     3
1  Jake     1
2  Lisa     4
3   Sue     2


name  rank_L  rank_R
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2

In [563]:
pop = pd.read_csv('us/state-population.csv') 
areas = pd.read_csv('us/state-areas.csv') 
abbrevs = pd.read_csv('us/state-abbrevs.csv')

In [566]:
print(pop.shape)
print(areas.shape)
print(abbrevs.shape)

(2544, 4)
(52, 2)
(51, 2)


In [565]:
print(pop.head()); 
print(areas.head()); 
print(abbrevs.head())

  state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0
        state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707
        state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA


In [579]:

print(areas.shape)
print(abbrevs.shape)
temp=pd.merge(areas,abbrevs,  how='outer')#you got left right inner outer
print(temp.shape)
# temp

(52, 2)
(51, 2)
(52, 3)


In [586]:
merged = pd.merge(pop, abbrevs, how='outer', left_on='state/region', right_on='abbreviation')
merged = merged.drop('abbreviation', 1) # drop duplicate info merged.head()

In [587]:
merged[:-10]

state/region     ages  year   population    state
0              AL  under18  2012    1117489.0  Alabama
1              AL    total  2012    4817528.0  Alabama
2              AL  under18  2010    1130966.0  Alabama
3              AL    total  2010    4785570.0  Alabama
4              AL  under18  2011    1125763.0  Alabama
...           ...      ...   ...          ...      ...
2529          USA  under18  2006   73757714.0      NaN
2530          USA    total  2007  301231207.0      NaN
2531          USA  under18  2007   74019405.0      NaN
2532          USA    total  2008  304093966.0      NaN
2533          USA  under18  2008   74104602.0      NaN

[2534 rows x 5 columns]

In [590]:
# merged[merged['state']=='Purte Rico']
merged.state.unique()

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'District of Columbia',
       'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York', 'North Carolina',
       'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
       'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
       'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'West Virginia', 'Wisconsin', 'Wyoming', nan], dtype=object)

In [591]:
merged.head()

state/region     ages  year  population    state
0           AL  under18  2012   1117489.0  Alabama
1           AL    total  2012   4817528.0  Alabama
2           AL  under18  2010   1130966.0  Alabama
3           AL    total  2010   4785570.0  Alabama
4           AL  under18  2011   1125763.0  Alabama

In [594]:
merged.isnull().any()

state/region    False
ages            False
year            False
population       True
state            True
dtype: bool

In [602]:
# merged[merged['population'].isnull()].head()
# type(merged['population'].isnull())
merged[merged['population'].isnull()]

state/region     ages  year  population state
2448           PR  under18  1990         NaN   NaN
2449           PR    total  1990         NaN   NaN
2450           PR    total  1991         NaN   NaN
2451           PR  under18  1991         NaN   NaN
2452           PR    total  1993         NaN   NaN
2453           PR  under18  1993         NaN   NaN
2454           PR  under18  1992         NaN   NaN
2455           PR    total  1992         NaN   NaN
2456           PR  under18  1994         NaN   NaN
2457           PR    total  1994         NaN   NaN
2458           PR    total  1995         NaN   NaN
2459           PR  under18  1995         NaN   NaN
2460           PR  under18  1996         NaN   NaN
2461           PR    total  1996         NaN   NaN
2462           PR  under18  1998         NaN   NaN
2463           PR    total  1998         NaN   NaN
2464           PR    total  1997         NaN   NaN
2465           PR  under18  1997         NaN   NaN
2466           PR    total  1999         NaN   NaN
2467           PR  under18  1999         NaN   NaN

In [601]:
# merged[merged['state'].isnull()]

state/region     ages  year   population state
2448           PR  under18  1990          NaN   NaN
2449           PR    total  1990          NaN   NaN
2450           PR    total  1991          NaN   NaN
2451           PR  under18  1991          NaN   NaN
2452           PR    total  1993          NaN   NaN
...           ...      ...   ...          ...   ...
2539          USA    total  2010  309326295.0   NaN
2540          USA  under18  2011   73902222.0   NaN
2541          USA    total  2011  311582564.0   NaN
2542          USA  under18  2012   73708179.0   NaN
2543          USA    total  2012  313873685.0   NaN

[96 rows x 5 columns]

In [610]:
# merged.loc[merged['state'].isnull(), 'state/region'].unique()
merged.loc[merged['state'].isnull()]['state/region'].unique()

array(['PR', 'USA'], dtype=object)

In [613]:
# merged.loc[merged['state/region'] == 'PR','state'] = 'Puerto Rico'
# merged.loc[merged['state/region'] == 'USA']['state'] = 'United States'
merged.isnull().any()

state/region    False
ages            False
year            False
population       True
state            True
dtype: bool

In [623]:
templ=[i for i in range(48)]
merged.loc[merged['state/region'] == 'PR', 'state']=templ
merged.loc[merged['state/region'] == 'PR']['state']

2448     0
2449     1
2450     2
2451     3
2452     4
2453     5
2454     6
2455     7
2456     8
2457     9
2458    10
2459    11
2460    12
2461    13
2462    14
2463    15
2464    16
2465    17
2466    18
2467    19
2468    20
2469    21
2470    22
2471    23
2472    24
2473    25
2474    26
2475    27
2476    28
2477    29
2478    30
2479    31
2480    32
2481    33
2482    34
2483    35
2484    36
2485    37
2486    38
2487    39
2488    40
2489    41
2490    42
2491    43
2492    44
2493    45
2494    46
2495    47
Name: state, dtype: object

In [624]:
merged.loc[merged['state/region'] == 'PR', 'state'] = 'Puerto Rico' 
merged.loc[merged['state/region'] == 'USA', 'state'] = 'United States' 
merged.isnull().any()

state/region    False
ages            False
year            False
population       True
state           False
dtype: bool

In [618]:
merged.loc[merged['state/region'] == 'PR']['state'] = 'Puerto Rico' 
#although
#merged.loc[merged['state/region'] == 'PR']['state']
#merged.loc[merged['state/region'] == 'PR', 'state']
#return the same thing, to assign collective value, you use the latter

<ipython-input-618-cf44f945e845>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged.loc[merged['state/region'] == 'PR']['state']='dd'


In [625]:
areas.head()

state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707

In [626]:
merged.head()

state/region     ages  year  population    state
0           AL  under18  2012   1117489.0  Alabama
1           AL    total  2012   4817528.0  Alabama
2           AL  under18  2010   1130966.0  Alabama
3           AL    total  2010   4785570.0  Alabama
4           AL  under18  2011   1125763.0  Alabama

state/region     ages  year  population        state
2448           PR  under18  1990         NaN  Puerto Rico
2449           PR    total  1990         NaN  Puerto Rico
2450           PR    total  1991         NaN  Puerto Rico
2451           PR  under18  1991         NaN  Puerto Rico
2452           PR    total  1993         NaN  Puerto Rico
2453           PR  under18  1993         NaN  Puerto Rico
2454           PR  under18  1992         NaN  Puerto Rico
2455           PR    total  1992         NaN  Puerto Rico
2456           PR  under18  1994         NaN  Puerto Rico
2457           PR    total  1994         NaN  Puerto Rico
2458           PR    total  1995         NaN  Puerto Rico
2459           PR  under18  1995         NaN  Puerto Rico
2460           PR  under18  1996         NaN  Puerto Rico
2461           PR    total  1996         NaN  Puerto Rico
2462           PR  under18  1998         NaN  Puerto Rico
2463           PR    total  1998         NaN  Puerto Rico
2464           PR    total  1997         NaN  Puerto Rico
2465           PR  under18  1997         NaN  Puerto Rico
2466           PR    total  1999         NaN  Puerto Rico
2467           PR  under18  1999         NaN  Puerto Rico

In [639]:
final = pd.merge(merged, areas, on='state', how='left')
# final = pd.merge(merged, areas, on='state')
final.shape

(2544, 6)

In [640]:
# final = pd.merge(merged, areas, on='state', how='left')
final = pd.merge(merged, areas, on='state')
final.shape

(2496, 6)

In [636]:
len(areas.state)

52

In [638]:
len(merged.state.unique())

53

In [641]:
final = pd.merge(merged, areas, on='state', how='left') 
final.head()

state/region     ages  year  population    state  area (sq. mi)
0           AL  under18  2012   1117489.0  Alabama        52423.0
1           AL    total  2012   4817528.0  Alabama        52423.0
2           AL  under18  2010   1130966.0  Alabama        52423.0
3           AL    total  2010   4785570.0  Alabama        52423.0
4           AL  under18  2011   1125763.0  Alabama        52423.0

In [645]:
final.isnull().any()

state/region     False
ages             False
year             False
population        True
state            False
area (sq. mi)     True
dtype: bool

In [650]:
final.loc[final['area (sq. mi)'].isnull()]

state/region     ages  year   population          state  area (sq. mi)
2496          USA  under18  1990   64218512.0  United States            NaN
2497          USA    total  1990  249622814.0  United States            NaN
2498          USA    total  1991  252980942.0  United States            NaN
2499          USA  under18  1991   65313018.0  United States            NaN
2500          USA  under18  1992   66509177.0  United States            NaN
2501          USA    total  1992  256514231.0  United States            NaN
2502          USA    total  1993  259918595.0  United States            NaN
2503          USA  under18  1993   67594938.0  United States            NaN
2504          USA  under18  1994   68640936.0  United States            NaN
2505          USA    total  1994  263125826.0  United States            NaN
2506          USA  under18  1995   69473140.0  United States            NaN
2507          USA  under18  1996   70233512.0  United States            NaN
2508          USA    total  1995  266278403.0  United States            NaN
2509          USA    total  1996  269394291.0  United States            NaN
2510          USA    total  1997  272646932.0  United States            NaN
2511          USA  under18  1997   70920738.0  United States            NaN
2512          USA  under18  1998   71431406.0  United States            NaN
2513          USA    total  1998  275854116.0  United States            NaN
2514          USA  under18  1999   71946051.0  United States            NaN
2515          USA    total  2000  282162411.0  United States            NaN
2516          USA  under18  2000   72376189.0  United States            NaN
2517          USA    total  1999  279040181.0  United States            NaN
2518          USA    total  2001  284968955.0  United States            NaN
2519          USA  under18  2001   72671175.0  United States            NaN
2520          USA    total  2002  287625193.0  United States            NaN
2521          USA  under18  2002   72936457.0  United States            NaN
2522          USA    total  2003  290107933.0  United States            NaN
2523          USA  under18  2003   73100758.0  United States            NaN
2524          USA    total  2004  292805298.0  United States            NaN
2525          USA  under18  2004   73297735.0  United States            NaN
2526          USA    total  2005  295516599.0  United States            NaN
2527          USA  under18  2005   73523669.0  United States            NaN
2528          USA    total  2006  298379912.0  United States            NaN
2529          USA  under18  2006   73757714.0  United States            NaN
2530          USA    total  2007  301231207.0  United States            NaN
2531          USA  under18  2007   74019405.0  United States            NaN
2532          USA    total  2008  304093966.0  United States            NaN
2533          USA  under18  2008   74104602.0  United States            NaN
2534          USA  under18  2013   73585872.0  United States            NaN
2535          USA    total  2013  316128839.0  United States            NaN
2536          USA    total  2009  306771529.0  United States            NaN
2537          USA  under18  2009   74134167.0  United States            NaN
2538          USA  under18  2010   74119556.0  United States            NaN
2539          USA    total  2010  309326295.0  United States            NaN
2540          USA  under18  2011   73902222.0  United States            NaN
2541          USA    total  2011  311582564.0  United States            NaN
2542          USA  under18  2012   73708179.0  United States            NaN
2543          USA    total  2012  313873685.0  United States            NaN

In [656]:
final[final['area (sq. mi)'].isnull()]['state'].unique()

array(['United States'], dtype=object)

In [657]:
final.dropna(inplace=True) 
final.head()

state/region     ages  year  population    state  area (sq. mi)
0           AL  under18  2012   1117489.0  Alabama        52423.0
1           AL    total  2012   4817528.0  Alabama        52423.0
2           AL  under18  2010   1130966.0  Alabama        52423.0
3           AL    total  2010   4785570.0  Alabama        52423.0
4           AL  under18  2011   1125763.0  Alabama        52423.0

In [658]:
final.isnull().any()

state/region     False
ages             False
year             False
population       False
state            False
area (sq. mi)    False
dtype: bool

In [667]:
# data2010 = final.query("year == 2010 & ages == 'total'")
data2010=final[(final['year']==2010 )&( final['ages']=='total')]
data2010

state/region   ages  year  population                 state  \
3              AL  total  2010   4785570.0               Alabama   
91             AK  total  2010    713868.0                Alaska   
101            AZ  total  2010   6408790.0               Arizona   
189            AR  total  2010   2922280.0              Arkansas   
197            CA  total  2010  37333601.0            California   
283            CO  total  2010   5048196.0              Colorado   
293            CT  total  2010   3579210.0           Connecticut   
379            DE  total  2010    899711.0              Delaware   
389            DC  total  2010    605125.0  District of Columbia   
475            FL  total  2010  18846054.0               Florida   
485            GA  total  2010   9713248.0               Georgia   
570            HI  total  2010   1363731.0                Hawaii   
581            ID  total  2010   1570718.0                 Idaho   
666            IL  total  2010  12839695.0              Illinois   
677            IN  total  2010   6489965.0               Indiana   
762            IA  total  2010   3050314.0                  Iowa   
773            KS  total  2010   2858910.0                Kansas   
858            KY  total  2010   4347698.0              Kentucky   
869            LA  total  2010   4545392.0             Louisiana   
954            ME  total  2010   1327366.0                 Maine   
965            MD  total  2010   5787193.0              Maryland   
1050           MA  total  2010   6563263.0         Massachusetts   
1061           MI  total  2010   9876149.0              Michigan   
1146           MN  total  2010   5310337.0             Minnesota   
1157           MS  total  2010   2970047.0           Mississippi   
1242           MO  total  2010   5996063.0              Missouri   
1253           MT  total  2010    990527.0               Montana   
1338           NE  total  2010   1829838.0              Nebraska   
1349           NV  total  2010   2703230.0                Nevada   
1434           NH  total  2010   1316614.0         New Hampshire   
1445           NJ  total  2010   8802707.0            New Jersey   
1530           NM  total  2010   2064982.0            New Mexico   
1541           NY  total  2010  19398228.0              New York   
1626           NC  total  2010   9559533.0        North Carolina   
1637           ND  total  2010    674344.0          North Dakota   
1722           OH  total  2010  11545435.0                  Ohio   
1733           OK  total  2010   3759263.0              Oklahoma   
1818           OR  total  2010   3837208.0                Oregon   
1829           PA  total  2010  12710472.0          Pennsylvania   
1914           RI  total  2010   1052669.0          Rhode Island   
1925           SC  total  2010   4636361.0        South Carolina   
2010           SD  total  2010    816211.0          South Dakota   
2021           TN  total  2010   6356683.0             Tennessee   
2106           TX  total  2010  25245178.0                 Texas   
2117           UT  total  2010   2774424.0                  Utah   
2202           VT  total  2010    625793.0               Vermont   
2213           VA  total  2010   8024417.0              Virginia   
2298           WA  total  2010   6742256.0            Washington   
2309           WV  total  2010   1854146.0         West Virginia   
2394           WI  total  2010   5689060.0             Wisconsin   
2405           WY  total  2010    564222.0               Wyoming   
2490           PR  total  2010   3721208.0           Puerto Rico   

      area (sq. mi)  
3           52423.0  
91         656425.0  
101        114006.0  
189         53182.0  
197        163707.0  
283        104100.0  
293          5544.0  
379          1954.0  
389            68.0  
475         65758.0  
485         59441.0  
570         10932.0  
581         83574.0  
666         57918.0  
677         36420.0  
762         56276.0  
773         82282.0  
858 

In [668]:
data2010.shape

(52, 6)

In [669]:
data2010.set_index('state', inplace=True)
data2010.head(10)

state/region   ages  year  population  area (sq. mi)
state                                                                    
Alabama                        AL  total  2010   4785570.0        52423.0
Alaska                         AK  total  2010    713868.0       656425.0
Arizona                        AZ  total  2010   6408790.0       114006.0
Arkansas                       AR  total  2010   2922280.0        53182.0
California                     CA  total  2010  37333601.0       163707.0
Colorado                       CO  total  2010   5048196.0       104100.0
Connecticut                    CT  total  2010   3579210.0         5544.0
Delaware                       DE  total  2010    899711.0         1954.0
District of Columbia           DC  total  2010    605125.0           68.0
Florida                        FL  total  2010  18846054.0        65758.0

In [670]:
density = data2010['population'] / data2010['area (sq. mi)']
density[:10]

state
Alabama                   91.287603
Alaska                     1.087509
Arizona                   56.214497
Arkansas                  54.948667
California               228.051342
Colorado                  48.493718
Connecticut              645.600649
Delaware                 460.445752
District of Columbia    8898.897059
Florida                  286.597129
dtype: float64

In [672]:
density.sort_values(ascending=False, inplace=True)
density.head()

state
District of Columbia    8898.897059
Puerto Rico             1058.665149
New Jersey              1009.253268
Rhode Island             681.339159
Connecticut              645.600649
dtype: float64