In [1]:
import numpy as np 
import pandas as pd
data = pd.Series([0.25, 0.5, 0.75, 1.0]) 
data


0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [2]:
print(data.values)
print(data.index)

[0.25 0.5  0.75 1.  ]
RangeIndex(start=0, stop=4, step=1)


In [3]:
print(data[1])
print(data[1:3])

0.5
1    0.50
2    0.75
dtype: float64


In [4]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [5]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [6]:
population_dict = {'California': 38332521, 'Texas': 26448193,
                               'New York': 19651127,
                               'Florida': 19552860,
                               'Illinois': 12882135}
population = pd.Series(population_dict) 
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [7]:
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [8]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
                 'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict) 
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [9]:
states = pd.DataFrame({'population': population, 'area': area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [10]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [11]:
states.columns

Index(['population', 'area'], dtype='object')

In [12]:
data = [{'a': i, 'b': 2 * i} for i in range(3)]
data

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]

In [13]:
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [14]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [16]:
type(population)

pandas.core.series.Series

In [17]:
pd.DataFrame({'population': population, 'area': area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [20]:
population_dict2 = {'California': 38332521, 'Texas': 26448193,
                               'New York': 19651127,
                               'Florida': 19552860,
                               'Illinois': 12882135,
                   'DC':10000}
population2 = pd.Series(population_dict2)
pd.DataFrame({'population2': population2, 'area': area})

population2      area
California     38332521  423967.0
DC                10000       NaN
Florida        19552860  170312.0
Illinois       12882135  149995.0
New York       19651127  141297.0
Texas          26448193  695662.0

In [21]:
pd.DataFrame(np.random.rand(3, 2), 
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

foo       bar
a  0.630440  0.602671
b  0.478404  0.860628
c  0.674212  0.296149

In [23]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [24]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [25]:
indA = pd.Index([1, 3, 5, 7, 9]) 
indB = pd.Index([2, 3, 5, 7, 11])

In [26]:
indA & indB

Int64Index([3, 5, 7], dtype='int64')

In [27]:
indA ^ indB

Int64Index([1, 2, 9, 11], dtype='int64')

In [28]:
import pandas as pd
data = pd.Series([0.25, 0.5, 0.75, 1.0],index=['a', 'b', 'c', 'd'])               
    
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [29]:
'a' in data

True

In [30]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [31]:
data['e'] = 1.25
data
data['e'] = 1.2
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.20
dtype: float64

In [32]:
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [33]:
data[0:2]

a    0.25
b    0.50
dtype: float64

In [34]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [35]:
# fancy indexing 
data[['a', 'e']]

a    0.25
e    1.20
dtype: float64

In [37]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5]) 
data

1    a
3    b
5    c
dtype: object

In [38]:
data[1]

'a'

In [39]:
data[1:3]

3    b
5    c
dtype: object

In [40]:
data.loc[1:3]

1    a
3    b
dtype: object

In [41]:
data.iloc[1:3] #iloc is the same as data[1:3]

3    b
5    c
dtype: object

In [42]:
area = pd.Series({'California': 423967, 'Texas': 695662, 'New York': 141297, 'Florida': 170312,
'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [43]:
data.area is data['area']

True

In [44]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [47]:
type(data.values)

numpy.ndarray

In [48]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [49]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [50]:
type(data.values[0])

numpy.ndarray

In [51]:
data.values[0].shape

(3,)

In [52]:
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [54]:
data.iloc[:2, :2]

area       pop
California  423967  38332521
Texas       695662  26448193

In [56]:
data.loc[:'Illinois', :'area']

area
California  423967
Texas       695662
New York    141297
Florida     170312
Illinois    149995

In [58]:
data.loc[data.density > 100, ['pop', 'area','density']]

pop    area     density
New York  19651127  141297  139.076746
Florida   19552860  170312  114.806121

In [60]:
data.iloc[0, 2] = 90 
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [61]:
data['Florida':'Illinois']

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [63]:
data.loc['Florida':'Illinois','area':'density']

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [64]:
data[1:3] 

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [65]:
area = pd.Series({1: 423967, 2: 695662, 3: 141297, 4: 170312,
5: 149995})
pop = pd.Series({1: 10, 2: 20, 3: 30, 4: 40,
5: 50})
data2 = pd.DataFrame({'a':area, 'b':pop})
data2

a   b
1  423967  10
2  695662  20
3  141297  30
4  170312  40
5  149995  50

In [68]:
data2.loc[1:3]

a   b
1  423967  10
2  695662  20
3  141297  30

In [69]:
data2[1:3]   

a   b
2  695662  20
3  141297  30

In [70]:
data2.iloc[1:3]

a   b
2  695662  20
3  141297  30

In [71]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4)) # this series has no explicit index
ser

0    6
1    3
2    7
3    4
dtype: int64

In [88]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)), columns=['A', 'B', 'C', 'D'])
df


A  B  C  D
0  1  7  5  1
1  4  0  9  5
2  8  0  9  2

In [74]:
type(np.exp(ser))

pandas.core.series.Series

In [76]:
np.sin(df * np.pi )

A             B             C             D
0 -7.347881e-16  1.102182e-15 -2.449294e-16 -7.347881e-16
1  8.572528e-16 -4.898587e-16  3.673940e-16  8.572528e-16
2  8.572528e-16 -2.449294e-16  6.123234e-16 -4.898587e-16

In [77]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662, 'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193, 'New York': 19651127}, name='population')

In [79]:
type(population / area)

pandas.core.series.Series

In [80]:
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [81]:
type(area.index)

pandas.core.indexes.base.Index

In [82]:
A = pd.Series([2, 4, 6], index=[0, 1, 2]) 
B = pd.Series([1, 3, 5], index=[1, 2, 3]) 
A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [83]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [93]:
df['A']=df['A'].add(df['B'])
df

A  B  C  D
0  8  7  5  1
1  4  0  9  5
2  8  0  9  2

In [90]:
df

A  B  C  D
0  1  7  5  1
1  4  0  9  5
2  8  0  9  2

In [94]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                 columns=list('AB'))
A

A   B
0  11  19
1   2   4

In [96]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)), columns=list('BAC'))
B

B  A  C
0  2  6  4
1  8  6  1
2  3  8  1

In [97]:
 A + B

A     B   C
0  17.0  21.0 NaN
1   8.0  12.0 NaN
2   NaN   NaN NaN

In [102]:
fill = A.stack()
print(fill)
type(fill) #pandas.core.series.Series

0  A    11
   B    19
1  A     2
   B     4
dtype: int64


pandas.core.series.Series

In [103]:
fill=fill.mean()
print(fill)


9.0
<class 'numpy.float64'>


In [105]:
A.add(B, fill_value=fill)   #should be a float value 

A     B     C
0  17.0  21.0  13.0
1   8.0  12.0  10.0
2  17.0  12.0  10.0

In [109]:
A = rng.randint(10, size=(3, 4))
print(type(A))
A

<class 'numpy.ndarray'>


array([[7, 3, 1, 5],
       [5, 9, 3, 5],
       [1, 9, 1, 9]])

In [110]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-2,  6,  2,  0],
       [-6,  6,  0,  4]])

In [111]:
df = pd.DataFrame(A, columns=list('QRST'))
df

Q  R  S  T
0  7  3  1  5
1  5  9  3  5
2  1  9  1  9

In [113]:
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -2  6  2  0
2 -6  6  0  4

In [114]:
# df.subtract(df['R'], axis=0)
df

Q  R  S  T
0  7  3  1  5
1  5  9  3  5
2  1  9  1  9

In [115]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0  4  0 -2  2
1 -4  0 -6 -4
2 -8  0 -8  0

In [116]:
df

Q  R  S  T
0  7  3  1  5
1  5  9  3  5
2  1  9  1  9

In [118]:
halfrow = df.iloc[0, ::2] 
print(type(halfrow))
halfrow

<class 'pandas.core.series.Series'>


Q    7
S    1
Name: 0, dtype: int64

In [125]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -2.0 NaN  2.0 NaN
2 -6.0 NaN  0.0 NaN

In [126]:
vals1 = np.array([1, None, 3, 4]) 
vals1


array([1, None, 3, 4], dtype=object)

In [127]:
vals2 = np.array([1, np.nan, 3, 4]) 
vals2.dtype

dtype('float64')

In [128]:
np.nansum(vals2)

8.0

In [131]:
x = pd.Series(range(1,10,2), dtype=int)
x

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [137]:
x[0]=None
x

0    NaN
1    3.0
2    5.0
3    7.0
4    9.0
dtype: float64

In [138]:
data = pd.Series([1, np.nan, 'hello', None])

In [141]:
print(data.isnull())
type(data.isnull())

0    False
1     True
2    False
3     True
dtype: bool


pandas.core.series.Series

In [142]:
data.notnull()

0     True
1    False
2     True
3    False
dtype: bool

In [143]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [144]:
data.dropna()

0        1
2    hello
dtype: object

In [145]:
df = pd.DataFrame([[1, np.nan, 2], [2, 3, 5],[np.nan, 4, 6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [146]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [148]:
df[3] = np.nan 
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [149]:
df.dropna(axis='columns', how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [150]:
df.dropna(axis='columns', how='any')

2
0  2
1  5
2  6

In [154]:
df.dropna(axis='columns', thresh=2)

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [160]:
data = pd.DataFrame(([1, np.nan, 2, None, 3] for i in range(3)), columns=list('abcde'))
data

a   b  c     d  e
0  1 NaN  2  None  3
1  1 NaN  2  None  3
2  1 NaN  2  None  3

In [161]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [162]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [164]:
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,18976457, 19378102,20851820, 25145561]
pop = pd.Series(populations, index=index) 
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [165]:
pop[('California', 2010):('Texas', 2000)]


(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
dtype: int64

In [166]:
pop[[i for i in pop.index if i[1] == 2010]]

(California, 2010)    37253956
(New York, 2010)      19378102
(Texas, 2010)         25145561
dtype: int64

In [167]:
index = pd.MultiIndex.from_tuples(index) 
index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [170]:
pop = pd.Series(populations, index=index) 
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [209]:
pop['Texas',]

2000    20851820
2010    25145561
dtype: int64

In [211]:
pop[:,2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [213]:
pop['Texas',2000]

20851820

In [221]:
pop.loc['New York':'Texas',2000:2010]

New York  2000    18976457
          2010    19378102
Texas     2000    20851820
          2010    25145561
dtype: int64